import React, { useRef } from "react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { User, Mail, Calendar, Pill, Utensils, Activity, TrendingUp, Flame, Camera, FileText, Download, Heart, ShieldAlert, ArrowRight, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/context/LanguageContext";
import { useAuth } from "@/context/AuthContext";
import { useApp } from "@/context/AppContext";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";

const Profile = () => {
    const { t } = useLanguage();
    const { user, updateUser } = useAuth();
    const { userMedications, getTodaysMeals, getTodaysCalories, getTodaysProtein, mealLog, hasOldData, clearOldData } = useApp();
    const fileInputRef = useRef<HTMLInputElement>(null);

    const todaysMeals = getTodaysMeals();
    const calories = getTodaysCalories();
    const protein = getTodaysProtein();

    const calorieGoal = 2000;
    const proteinGoal = 60;
    const calPercentage = Math.min((calories / calorieGoal) * 100, 100);
    const proteinPercentage = Math.min((protein / proteinGoal) * 100, 100);

    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            if (file.size > 2 * 1024 * 1024) {
                toast.error("Image too large. Please select an image under 2MB.");
                return;
            }
            const reader = new FileReader();
            reader.onloadend = () => {
                updateUser({ profileImage: reader.result as string });
                toast.success("Profile photo updated!");
            };
            reader.readAsDataURL(file);
        }
    };

    const generateHealthReport = (days: number) => {
        const doc = new jsPDF();
        const userName = user?.name || "User";
        const startDate = new Date();
        startDate.setDate(startDate.getDate() - days);

        // Title & Header
        doc.setFontSize(22);
        doc.setTextColor(16, 185, 129); // Emerald-500
        doc.text("MediNutri Health Report", 14, 22);

        doc.setFontSize(12);
        doc.setTextColor(100, 116, 139); // Slate-500
        doc.text(`Patient: ${userName}`, 14, 32);
        doc.text(`Email: ${user?.email || "N/A"}`, 14, 38);
        doc.text(`Report Period: Last ${days} days (${startDate.toLocaleDateString()} - ${new Date().toLocaleDateString()})`, 14, 44);

        // Medication Section
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("Active Medications", 14, 60);

        const currentMeds = userMedications.map(med => [med.name, med.dosage, med.frequency]);
        autoTable(doc, {
            startY: 65,
            head: [['Medication', 'Dosage', 'Frequency']],
            body: currentMeds.length > 0 ? currentMeds : [['No medications listed', '-', '-']],
            theme: 'striped',
            headStyles: { fillColor: [16, 185, 129] }
        });

        // Food Intake Section
        let lastY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(16);
        doc.text("Nutritional Intake & Macros", 14, lastY);

        // Filter meal log for the period
        const filteredMeals = mealLog.filter(meal => {
            const mealDate = new Date(meal.timestamp);
            return mealDate >= startDate;
        }).sort((a, b) => b.timestamp - a.timestamp);

        const mealData = filteredMeals.map(meal => [
            new Date(meal.timestamp).toLocaleDateString(),
            meal.mealType.toUpperCase(),
            meal.food.name,
            `${meal.food.calories} kcal`,
            `${meal.food.protein}g`
        ]);

        autoTable(doc, {
            startY: lastY + 5,
            head: [['Date', 'Meal', 'Food Item', 'Calories', 'Protein']],
            body: mealData.length > 0 ? mealData : [['No meals logged in this period', '-', '-', '-', '-']],
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] } // Blue-500
        });

        // Footer disclaimer
        const finalY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("This report is generated by MediNutri. Always consult your doctor for medical advice.", 14, finalY);

        doc.save(`${userName.replace(/\s+/g, '_')}_report.pdf`);
        toast.success(`Health report generated for the last ${days} days!`);
    };

    return (
        <div className="relative min-h-screen overflow-hidden bg-slate-950 px-4 md:px-0">
            {/* Background Decorative Mesh */}
            <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-primary/10 rounded-full blur-[120px] -translate-y-1/2 opacity-50" />
            <div className="absolute bottom-0 right-1/4 w-[600px] h-[600px] bg-emerald-500/10 rounded-full blur-[150px] translate-y-1/2 opacity-30" />

            <div className="relative container py-12 space-y-12 max-w-6xl animate-in fade-in duration-800">
                {/* Refined Header */}
                <div className="relative overflow-visible">
                    <div className="flex flex-col md:flex-row gap-12 items-center md:items-start">
                        {/* Circular Avatar with Green Border */}
                        <div className="relative shrink-0 group">
                            <input
                                type="file"
                                ref={fileInputRef}
                                className="hidden"
                                accept="image/*"
                                onChange={handleImageUpload}
                            />
                            <div className="relative h-48 w-48 rounded-full p-1 bg-gradient-to-br from-primary/50 to-emerald-500/50 shadow-[0_0_40px_rgba(16,185,129,0.2)] group-hover:scale-105 transition-transform duration-500">
                                <button
                                    onClick={() => fileInputRef.current?.click()}
                                    className="relative h-full w-full rounded-full overflow-hidden bg-slate-900 border-2 border-slate-950 flex items-center justify-center text-white"
                                >
                                    {user?.profileImage ? (
                                        <img src={user.profileImage} alt="Profile" className="h-full w-full object-cover" />
                                    ) : (
                                        <User className="h-20 w-20 text-slate-700" />
                                    )}
                                    <div className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                        <Camera className="h-10 w-10 text-white" />
                                    </div>
                                </button>
                            </div>
                        </div>

                        {/* User Details */}
                        <div className="space-y-8 flex-1 text-center md:text-left">
                            <div className="space-y-2">
                                <div className="flex flex-col md:flex-row md:items-baseline md:gap-6 items-center justify-center md:justify-start">
                                    <h1 className="text-8xl font-black tracking-tighter text-white lowercase">
                                        {user?.name?.split(' ')[0]}
                                    </h1>
                                    <Link to="/complete-profile">
                                        <Button variant="outline" size="sm" className="hidden md:flex rounded-full border-white/10 bg-white/5 hover:bg-primary hover:border-primary text-xs font-black uppercase tracking-widest px-6 h-10 gap-2 transition-all">
                                            Edit Profile
                                            <ArrowRight className="h-3 w-3" />
                                        </Button>
                                    </Link>
                                </div>

                                <div className="flex flex-col md:flex-row flex-wrap gap-4 mt-6 justify-center md:justify-start">
                                    <div className="flex items-center gap-3 bg-slate-900/60 backdrop-blur-md px-8 py-3.5 rounded-full border border-white/10 text-slate-300 shadow-xl">
                                        <Mail className="h-5 w-5 text-primary" />
                                        <span className="text-lg font-bold lowercase tracking-tight">{user?.email}</span>
                                    </div>
                                    <div className="flex items-center gap-3 bg-slate-900/60 backdrop-blur-md px-8 py-3.5 rounded-full border border-white/10 text-slate-300 shadow-xl">
                                        <Calendar className="h-5 w-5 text-primary" />
                                        <span className="text-lg font-bold">Member since Feb 2025</span>
                                    </div>
                                </div>
                            </div>

                            {/* Mobile Edit Button */}
                            <Link to="/complete-profile" className="block md:hidden">
                                <Button variant="outline" className="w-full rounded-full border-white/10 bg-white/5 px-8 h-12 text-sm font-black uppercase tracking-widest gap-2">
                                    Edit Profile
                                    <ArrowRight className="h-4 w-4" />
                                </Button>
                            </Link>

                            {/* Health Report Generation Section */}
                            <div className="relative group p-8 md:p-10 rounded-[3rem] bg-slate-900/60 backdrop-blur-xl border border-white/5 shadow-3xl max-w-2xl mx-auto md:mx-0">
                                <div className="flex flex-col sm:flex-row items-center gap-8">
                                    <div className="shrink-0 flex flex-col items-center">
                                        <div className="h-16 w-16 rounded-[1.5rem] bg-primary/10 flex items-center justify-center border border-primary/20 shadow-inner group-hover:scale-110 transition-transform duration-500">
                                            <FileText className="h-8 w-8 text-primary" />
                                        </div>
                                        <span className="mt-4 font-black text-white uppercase tracking-widest text-[10px] opacity-70 text-center">Generate Health Report</span>
                                    </div>

                                    <div className="grid grid-cols-2 gap-3 w-full">
                                        {[
                                            { label: "1 Week", days: 7 },
                                            { label: "2 Weeks", days: 14 },
                                            { label: "3 Weeks", days: 21 },
                                            { label: "1 Month", days: 30 }
                                        ].map((opt) => (
                                            <button
                                                key={opt.days}
                                                onClick={() => generateHealthReport(opt.days)}
                                                className="px-6 py-4 bg-slate-800/50 hover:bg-primary transition-all rounded-2xl text-sm font-black text-white flex items-center justify-center gap-3 border border-white/5 shadow-xl group/btn"
                                            >
                                                <Download className="h-4 w-4 opacity-50 group-hover/btn:opacity-100 transition-opacity" />
                                                {opt.label}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Old Data Cleanup Prompt */}
                {hasOldData && (
                    <div className="mt-4 p-6 bg-red-500/10 rounded-[2.5rem] border border-red-500/20 flex flex-col sm:flex-row items-center justify-between gap-6 animate-in slide-in-from-top duration-700">
                        <div className="flex items-center gap-4 text-center sm:text-left">
                            <div className="h-12 w-12 rounded-2xl bg-red-500/20 flex items-center justify-center shrink-0">
                                <Trash2 className="h-6 w-6 text-red-400" />
                            </div>
                            <div>
                                <p className="font-black text-white text-lg leading-tight">Optimization Required</p>
                                <p className="text-sm font-bold text-slate-400">Your history exceeds 2 months. Delete old data to keep MediNutri fast?</p>
                            </div>
                        </div>
                        <div className="flex gap-3">
                            <Button
                                variant="destructive"
                                onClick={() => {
                                    clearOldData();
                                    toast.success("Ancient history cleared successfully!");
                                }}
                                className="rounded-2xl h-14 px-8 font-black gap-2 shadow-xl shadow-red-500/10"
                            >
                                Yes, Delete Old Data
                            </Button>
                        </div>
                    </div>
                )}

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                    {/* Health Summary & Meals */}
                    <div className="lg:col-span-8 space-y-12">
                        <section>
                            <div className="flex items-center justify-between mb-8 px-2">
                                <div className="flex items-center gap-3">
                                    <div className="h-12 w-12 rounded-[1.5rem] bg-orange-500/10 flex items-center justify-center border border-orange-500/20">
                                        <Activity className="h-6 w-6 text-orange-500" />
                                    </div>
                                    <h2 className="text-4xl font-black tracking-tight text-white">{t.auth.healthSummary}</h2>
                                </div>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-8 text-white">
                                <Card className="border border-white/10 shadow-3xl bg-slate-900/80 backdrop-blur-xl rounded-[3rem] overflow-hidden">
                                    <CardContent className="pt-10 p-10">
                                        <div className="flex justify-between items-start mb-8">
                                            <div>
                                                <p className="text-slate-400 font-black uppercase tracking-widest text-[10px] mb-2">Daily Energy</p>
                                                <h3 className="text-xl font-black">{t.diet.todaysCalories}</h3>
                                            </div>
                                            <div className="h-14 w-14 rounded-[1.5rem] bg-orange-500/20 flex items-center justify-center">
                                                <TrendingUp className="h-7 w-7 text-orange-500" />
                                            </div>
                                        </div>
                                        <div className="flex items-baseline gap-2 mb-6">
                                            <span className="text-6xl font-black text-white">{Math.round(calories)}</span>
                                            <span className="text-slate-400 font-black text-lg">/ {calorieGoal} kcal</span>
                                        </div>
                                        <div className="space-y-3">
                                            <Progress value={calPercentage} className="h-4 bg-white/5 rounded-full" />
                                            <div className="flex justify-between text-xs font-black text-slate-500 uppercase tracking-tighter">
                                                <span>Vitality Level</span>
                                                <span>{Math.round(calPercentage)}%</span>
                                            </div>
                                        </div>
                                    </CardContent>
                                </Card>

                                <Card className="border border-white/10 shadow-3xl bg-slate-900/80 backdrop-blur-xl rounded-[3rem] overflow-hidden">
                                    <CardContent className="pt-10 p-10">
                                        <div className="flex justify-between items-start mb-8">
                                            <div>
                                                <p className="text-slate-400 font-black uppercase tracking-widest text-[10px] mb-2">Muscle Strength</p>
                                                <h3 className="text-xl font-black">{t.diet.protein}</h3>
                                            </div>
                                            <div className="h-14 w-14 rounded-[1.5rem] bg-blue-500/20 flex items-center justify-center">
                                                <Activity className="h-7 w-7 text-blue-400" />
                                            </div>
                                        </div>
                                        <div className="flex items-baseline gap-2 mb-6">
                                            <span className="text-6xl font-black text-white">{Math.round(protein)}g</span>
                                            <span className="text-slate-400 font-black text-lg">/ {proteinGoal}g</span>
                                        </div>
                                        <div className="space-y-3">
                                            <Progress value={proteinPercentage} className="h-4 bg-white/5 rounded-full" />
                                            <div className="flex justify-between text-xs font-black text-slate-500 uppercase tracking-tighter">
                                                <span>Protein Balance</span>
                                                <span>{Math.round(proteinPercentage)}%</span>
                                            </div>
                                        </div>
                                    </CardContent>
                                </Card>
                            </div>
                        </section>

                        <section className="mt-12">
                            <div className="flex items-center gap-3 mb-8 px-2">
                                <div className="h-12 w-12 rounded-[1.5rem] bg-blue-500/10 flex items-center justify-center border border-blue-500/20">
                                    <User className="h-6 w-6 text-blue-400" />
                                </div>
                                <h2 className="text-4xl font-black tracking-tight text-white uppercase">Personal Health Profile</h2>
                            </div>

                            <Card className="border border-white/10 shadow-3xl bg-slate-900/60 backdrop-blur-xl rounded-[3.5rem] overflow-hidden">
                                <CardContent className="p-10">
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-10">
                                        <div className="space-y-1">
                                            <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Age</p>
                                            <p className="text-3xl font-black text-white">{user?.age || "N/A"}</p>
                                        </div>
                                        <div className="space-y-1">
                                            <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Gender</p>
                                            <p className="text-3xl font-black text-white capitalize">{user?.gender || "N/A"}</p>
                                        </div>
                                        <div className="space-y-1">
                                            <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Height</p>
                                            <p className="text-3xl font-black text-white">{user?.height} <span className="text-sm font-bold text-slate-500">cm</span></p>
                                        </div>
                                        <div className="space-y-1">
                                            <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Weight</p>
                                            <p className="text-3xl font-black text-white">{user?.weight} <span className="text-sm font-bold text-slate-500">kg</span></p>
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                        <div className="p-8 bg-white/5 rounded-[2.5rem] border border-white/5">
                                            <div className="flex items-center gap-4 mb-4">
                                                <div className="h-10 w-10 rounded-xl bg-red-500/10 flex items-center justify-center">
                                                    <Heart className="h-5 w-5 text-red-400" />
                                                </div>
                                                <h4 className="font-black text-white uppercase tracking-wider">Medical Conditions</h4>
                                            </div>
                                            <div className="flex flex-wrap gap-2">
                                                {user?.medicalConditions?.length ? user.medicalConditions.map(c => (
                                                    <span key={c} className="px-4 py-2 bg-red-500/10 text-red-400 rounded-xl text-xs font-black uppercase tracking-tight border border-red-500/20">{c}</span>
                                                )) : <span className="text-slate-500 font-bold italic">No conditions reported</span>}
                                            </div>
                                        </div>

                                        <div className="p-8 bg-white/5 rounded-[2.5rem] border border-white/5">
                                            <div className="flex items-center gap-4 mb-4">
                                                <div className="h-10 w-10 rounded-xl bg-orange-500/10 flex items-center justify-center">
                                                    <ShieldAlert className="h-5 w-5 text-orange-400" />
                                                </div>
                                                <h4 className="font-black text-white uppercase tracking-wider">Known Allergies</h4>
                                            </div>
                                            <div className="flex flex-wrap gap-2">
                                                {user?.allergies?.length ? user.allergies.map(a => (
                                                    <span key={a} className="px-4 py-2 bg-orange-500/10 text-orange-400 rounded-xl text-xs font-black uppercase tracking-tight border border-orange-500/20">{a}</span>
                                                )) : <span className="text-slate-500 font-bold italic">No allergies reported</span>}
                                            </div>
                                        </div>
                                    </div>

                                    <div className="mt-8 p-8 bg-emerald-500/5 rounded-[2.5rem] border border-emerald-500/10 flex items-center justify-between">
                                        <div className="flex items-center gap-4">
                                            <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 flex items-center justify-center">
                                                <Activity className="h-6 w-6 text-emerald-400" />
                                            </div>
                                            <div>
                                                <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Calculated BMI</p>
                                                <p className="text-3xl font-black text-emerald-400">
                                                    {user?.weight && user?.height ? (user.weight / ((user.height / 100) ** 2)).toFixed(1) : "N/A"}
                                                </p>
                                            </div>
                                        </div>
                                        <Link to="/complete-profile">
                                            <Button variant="ghost" className="rounded-2xl h-14 px-8 font-black gap-2 hover:bg-white/5">
                                                {t.settings.settings}
                                                <ArrowRight className="h-4 w-4" />
                                            </Button>
                                        </Link>
                                    </div>
                                </CardContent>
                            </Card>
                        </section>

                        <section>
                            <div className="flex items-center gap-3 mb-8 px-2">
                                <div className="h-12 w-12 rounded-[1.5rem] bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20">
                                    <Utensils className="h-6 w-6 text-emerald-500" />
                                </div>
                                <h2 className="text-4xl font-black tracking-tight text-white">{t.auth.recentMeals}</h2>
                            </div>

                            {todaysMeals.length > 0 ? (
                                <div className="grid grid-cols-1 gap-6">
                                    {todaysMeals.map((meal) => (
                                        <div
                                            key={meal.id}
                                            className="flex items-center gap-6 p-8 bg-slate-900/40 backdrop-blur-sm rounded-[3rem] border border-white/5 shadow-xl transition-all"
                                        >
                                            <div className="h-20 w-20 rounded-[2rem] bg-gradient-to-br from-white/5 to-white/10 flex items-center justify-center border border-white/10 shrink-0">
                                                <Utensils className="h-10 w-10 text-emerald-400" />
                                            </div>
                                            <div className="flex-1 min-w-0">
                                                <div className="flex flex-wrap items-center gap-3">
                                                    <p className="font-black text-2xl text-white truncate">{meal.food.name}</p>
                                                    <span className="px-3 py-1 bg-white/5 rounded-xl text-[10px] font-black text-slate-400 uppercase tracking-widest">{meal.mealType}</span>
                                                </div>
                                                <p className="text-base font-bold text-slate-500 mt-1 text-white/40">Logged today at {new Date(meal.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p>
                                            </div>
                                            <div className="text-right shrink-0">
                                                <div className="flex items-center gap-1 justify-end">
                                                    <Flame className="h-4 w-4 text-orange-500" />
                                                    <p className="font-black text-3xl text-emerald-400">{meal.food.calories}</p>
                                                </div>
                                                <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest mt-1 text-white">{meal.food.protein}g Protein</p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <Card className="border-2 border-dashed border-white/5 bg-white/5 rounded-[4rem]">
                                    <CardContent className="py-24 text-center">
                                        <div className="w-24 h-24 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-8">
                                            <Utensils className="h-12 w-12 text-slate-600" />
                                        </div>
                                        <p className="text-slate-400 text-xl font-black tracking-tight">{t.auth.noMeals}</p>
                                        <p className="text-slate-500 text-base mt-2">Start your health journey by logging some meals.</p>
                                    </CardContent>
                                </Card>
                            )}
                        </section>
                    </div>

                    <div className="lg:col-span-4 space-y-12">
                        <section>
                            <div className="flex items-center gap-3 mb-8 px-2">
                                <div className="h-12 w-12 rounded-[1.5rem] bg-primary/10 flex items-center justify-center border border-primary/20">
                                    <Pill className="h-6 w-6 text-primary" />
                                </div>
                                <h2 className="text-4xl font-black tracking-tight text-white mb-0">{t.auth.activeMedications}</h2>
                            </div>

                            {userMedications.length > 0 ? (
                                <div className="space-y-6">
                                    {userMedications.map((med) => (
                                        <Card key={med.id} className="border border-white/5 shadow-2xl bg-gradient-to-br from-slate-900/90 to-slate-950/90 backdrop-blur-xl rounded-[3rem] overflow-hidden">
                                            <CardContent className="p-10">
                                                <div className="flex items-start gap-6">
                                                    <div className="h-16 w-16 rounded-[1.5rem] bg-primary/10 flex items-center justify-center shadow-xl shadow-black/20 shrink-0">
                                                        <Pill className="h-8 w-8 text-primary" />
                                                    </div>
                                                    <div className="space-y-3 min-w-0">
                                                        <p className="font-black text-2xl text-white leading-none truncate">{med.name}</p>
                                                        <div className="flex flex-wrap gap-3">
                                                            <span className="px-4 py-1.5 bg-white/5 rounded-xl text-xs font-black text-slate-300 uppercase tracking-tight">{med.dosage}</span>
                                                            <span className="px-4 py-1.5 bg-white/5 rounded-xl text-xs font-black text-slate-300 uppercase tracking-tight">{med.frequency}</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </CardContent>
                                        </Card>
                                    ))}
                                </div>
                            ) : (
                                <Card className="border-2 border-dashed border-white/5 bg-white/5 rounded-[4rem] text-center">
                                    <CardContent className="py-24 px-10">
                                        <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-6">
                                            <Pill className="h-10 w-10 text-slate-600" />
                                        </div>
                                        <p className="text-slate-400 font-black text-lg">{t.auth.noMedications}</p>
                                    </CardContent>
                                </Card>
                            )}
                        </section>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Profile;
